python compute-dsc.py -p outputs\DeepLab_DUC_HDC -o outputs\DeepLab_DUC_HDC.txt
python compute-dsc.py -p outputs\DeepLabResNet -o outputs\DeepLabResNet.txt
python compute-dsc.py -p outputs\DeepLabXception -o outputs\DeepLabXception.txt
python compute-dsc.py -p outputs\ENet -o outputs\ENet.txt
python compute-dsc.py -p outputs\FCN8 -o outputs\FCN8.txt
python compute-dsc.py -p outputs\GCN -o outputs\GCN.txt
python compute-dsc.py -p outputs\PSPDenseNet -o outputs\PSPDenseNet.txt
python compute-dsc.py -p outputs\PSPNet -o outputs\PSPNet.txt
python compute-dsc.py -p outputs\SegNet -o outputs\SegNet.txt
python compute-dsc.py -p outputs\SegResNet -o outputs\SegResNet.txt
python compute-dsc.py -p outputs\UNet -o outputs\UNet.txt
python compute-dsc.py -p outputs\UNetResnet -o outputs\UNetResnet.txt
python compute-dsc.py -p outputs\UperNet -o outputs\UperNet.txt
