name: segnet2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.3.0
  - blas=1.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cloudpickle=2.2.0
  - cudatoolkit=10.0.130
  - cytoolz=0.12.0
  - dask-core=2022.2.0
  - decorator=5.1.1
  - freetype=2.12.1
  - fsspec=2022.10.0
  - imagecodecs-lite=2019.12.3
  - imageio=2.13.1
  - importlib-metadata=4.11.4
  - intel-openmp=2021.4.0
  - joblib=1.2.0
  - jpeg=9e
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.8
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - locket=1.0.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - networkx=2.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - olefile=0.46
  - openssl=1.1.1q
  - packaging=21.3
  - partd=1.3.0
  - pillow=6.2.0
  - pip=22.2.2
  - protobuf=3.20.1
  - pycparser=2.21
  - pyparsing=3.0.9
  - python=3.7.13
  - python_abi=3.7
  - pytorch=1.1.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - scikit-image=0.19.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - tensorboard=1.14.0
  - threadpoolctl=3.1.0
  - tifffile=2020.6.3
  - tk=8.6.12
  - toolz=0.12.0
  - torchvision=0.3.0
  - tqdm=4.32.2
  - typing_extensions=4.4.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.2.2
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - future==0.18.2
    - opencv-python==4.1.0.25
