python train.py -c config\DeepLab_DUC_HDC.json
python train.py -c config\DeepLabResNet.json
python train.py -c config\DeepLabXception.json
python train.py -c config\ENet.json
python train.py -c config\FCN8.json
python train.py -c config\GCN.json
python train.py -c config\PSPDenseNet.json
python train.py -c config\PSPNet.json
python train.py -c config\SegNet.json
python train.py -c config\SegResNet.json
python train.py -c config\UNet.json
python train.py -c config\UNetResnet.json
python train.py -c config\UperNet.json